### ISSUE TITLE
Choose option button not align on safari

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/Goods2Go-Internal-25th-Mar#9]
Bug - Showing thin spacebar below choose option button when user hover on product tile in safari.
Exp - Should not show spacebar below button on hover on product tile in safari.
Ref Link - https://drive.google.com/file/d/1oCzZLYon_0r0mccgpieh2VB2kkf2Ef_u/view

**Comment by ui-abrarul** [comment]
![Screenshot 2022-06-07 at 1 14 06 PM](https://user-images.githubusercontent.com/100340013/172325411-dcf209ba-2a3e-4365-bac8-d89b4dc82dc4.png)

**Comment by ankitcedcoss** [comment]
Bug Fixed
